Knowledge_Graph/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #图谱展示
    path('Graphapp/', include(('apps.Graphapp.urls',"Graphapp"),namespace='Graphapp')),
    #成分对比分析
    path('Analysis/', include(('apps.Analysis.urls',"Analysis"),namespace='Analysis')),
    #方剂知识库
    path('Formula/', include(('apps.Formula.urls',"Formula"),namespace='Formula')),
    #药材知识库
    path('Herb/', include(('apps.Herb.urls',"Herb"),namespace='Herb')),
    #组分知识库
    path('Ingredients/', include(('apps.Ingredients.urls',"Ingredients"),namespace='Ingredients')),
    #靶标知识库
    path('Target/', include(('apps.Target.urls',"Target"),namespace='Target')),
    #方剂配伍
    path('Combination/', include(('apps.Combination.urls',"Combination"),namespace='Combination'))
  ]

apps/Formula/urls.py
from django.urls import path
from apps.Formula import views


urlpatterns = [
 #方剂信息展示页面
 path('Search_recipe/<str:name>', views.Search_recipe, name='Search_recipe'),
 path('index/', views.index, name='index'),
  #不良反应
 path('ADRindex/', views.ADRindex, name='ADRindex'),
 path('ADR/<str:name>', views.ADR, name='ADR')
 ]

apps/Herb/urls.py
from django.urls import path

from apps.Herb import views

urlpatterns = [
        #药材信息展示页面
 path('herbindex/', views.herbindex, name='herbindex'),
 path('Search_herb/<str:name>/', views.Search_herb, name='Search_herb')
 ]

apps/Formula/models.py
from django.db import models

# Create your models here.

apps/Formula/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from apps.Graphapp.models import Formulas, Forcom,Herbs
# Create your views here.

#方剂知识库
def index(request):
    search_text=request.GET.get('search-recipe-text')
    if not search_text:
        return render(request, 'index.html')
    #TODO: 搜索拉丁文名
    #模糊搜索
    recipes=Formulas.objects.filter(formulas_name__contains=search_text,mark=1).values_list('formulas_name',flat=True)
    #搜索不到
    if not recipes:
        return render(request, 'index.html', {'search_text':search_text})
    p = Paginator(recipes,10)   #分页，10个一页
    # 获取 url 中的页码
    page = request.GET.get('page',1)
    # 将导航对象相应的页码内容返回给 articles
    recipe_list = p.get_page(page)
    return render(request, 'index.html', {'search_text':search_text, 'recipe_list': recipe_list})
def Search_recipe(request,name):
    recipe=Formulas.objects.filter(formulas_name=name,mark=1)
    reccoms=Forcom.objects.filter(formulas_no=recipe[0].formulas_no,mark=1)
    return render(request, 'Search_recipe.html', {'reccoms':reccoms, 'recipe':recipe[0]})
#不良反应界面
def ADRindex(request):
    search_text=request.GET.get('search-text')
    if not search_text:
        return render(request, 'ADRindex.html')
    #TODO: 搜索拉丁文名
    #模糊搜索
    recipes=Formulas.objects.filter(formulas_name__contains=search_text,mark=1).values_list('formulas_name',flat=True)
    #搜索不到
    if not recipes:
        return render(request, 'ADRindex.html', {'search_text':search_text})
    p = Paginator(recipes,10)   #分页，10个一页
    # 获取 url 中的页码
    page = request.GET.get('page',1)
    # 将导航对象相应的页码内容返回给 articles
    recipe_list = p.get_page(page)
    return render(request, 'ADRindex.html', {'search_text':search_text, 'recipe_list': recipe_list})
def ADR(request,name):
    recipe=Formulas.objects.filter(formulas_name=name,mark=1)
    reccoms=Forcom.objects.filter(formulas_no=recipe[0].formulas_no,mark=1).values_list('herbs_name',flat=True)
    herbs={}
    for reccom in reccoms:
        herb=Herbs.objects.filter(herbs_name=reccom)
        if herb:
            if herb[0].adverserea == 'null':
                herb[0].adverserea='暂无'
                herbs[herb[0].herbs_name]=herb[0].adverserea
    return render(request, 'ADR.html', {'recipe':recipe[0],'herbs':herbs})

apps/Formula/templates/ADR.html
{% extends 'base.html' %}
{% load static %}
{% block title %}不良反应{% endblock %}
{% block content %}
    <br>
        <div class="container-fluid">
            <!-- Page Header-->
            <header>
                <h1 class="h3 display">不良反应</h1>
            </header>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{% url 'Formula:ADRindex' %}" method="get">
                            <div class="form-group row" style="margin-left: 25%;" >
                                <label class="form-control-label">方剂名称</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="search-text" placeholder="示例：" style="vertical-align: middle;">
                                </div>
                                <div class="col-sm-2 " style="text-align: right;">
                                    <button class="btn btn-primary" >检索</button>
                                </div>
                            </div>
                             </form>
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h2 class="h5">{{ recipe.formulas_name }}</h2>
                        {% if herbs %}
                            <table class="table table-hover">
                              <tbody>
                                <tr>
                                  <th width="30%" scope="row">【组分名称】</th>
                                  <td>【不良反应】</td>
                                </tr>
                                {% for key,v in herbs.items %}
                                <tr>
                                  <th width="30%" scope="row">{{ key }}</th>
                                  <td>{{ v }}</td>
                                </tr>
                              {% endfor %}
                              </tbody>
                            </table>
                        {% else %}
                            <div class="row" style="text-align: center"><p style="margin:0 auto;width:200px;"><p>没有查找到对应成分</p></div>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

apps/Formula/templates/ADRindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %}不良反应{% endblock %}
{% block content %}
    <br>
        <div class="container-fluid">
            <!-- Page Header-->
            <header>
                <h1 class="h3 display">不良反应</h1>
            </header>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{% url 'Formula:ADRindex' %}" method="get">
                            <div class="form-group row" style="margin-left: 25%;" >
                                <label class="form-control-label">方剂名称</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="search-text" placeholder="示例：" style="vertical-align: middle;">
                                </div>
                                <div class="col-sm-2 " style="text-align: right;">
                                    <button class="btn btn-primary" >检索</button>
                                </div>
                            </div>
                             </form>
                        </div>
                    </div>
                </div>
            </div>
        {% if search_text  %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {% if recipe_list %}
                            <h2 class="h5">搜索结果</h2>
                                <div class="list-group">
                                {% for recipe in recipe_list %}
                                  <a href="{% url 'Formula:ADR' recipe %} " class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                      <h5 class="mb-1" >{{ recipe }}</h5>
                                    </div>
                                  </a>
                                {% endfor %}
                                </div>
                                <br>
                                <div class="pagination row">
                                    <div class="m-auto">
                                        <span class="step-links">
                                            <!-- 如果不是第一页，则显示上翻按钮 -->
                                            {% if recipe_list.has_previous %}
                                                <a href="?search-recipe-text={{ search_text }}&page=1" class="btn btn-success">
                                                    &laquo; 1
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.previous_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.previous_page_number }}
                                                </a>
                                            {% endif %}

                                            <!-- 当前页面 -->
                                            <span class="current btn btn-success btn-lg">
                                                {{ recipe_list.number }}
                                            </span>

                                            <!-- 如果不是最末页，则显示下翻按钮 -->
                                            {% if recipe_list.has_next %}
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.next_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.next_page_number }}
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.paginator.num_pages }}"
                                                   class="btn btn-success"
                                                >
                                                    {{ recipe_list.paginator.num_pages }} &raquo;
                                                </a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <h2 class="card-title">未找到相关结果</h2>
                                <br>
                                <p class="card-subtitle mb-2 text-muted">您可以:</p>
                                <p class="card-text">1.检查检索词是否有误或者过于复杂</p>
                                <p class="card-text">2.在其他栏目中搜索“{{ search_text }}”</p>
                                <a href="{% url 'Formula:ADRindex' %}" class="card-link">返回</a>
                             {% endif %}
                        </div>
                    </div>
                </div>
        </div>
{% endif %}
        </div>
{% endblock %}

apps/Formula/templates/Search_recipe.html
{% extends 'base.html' %}
{% load static %}
{% block title %}中药方剂知识库{% endblock %}

{% block content %}
    <!-- Counts Section -->
    <br>
        <div class="container-fluid">
            <!-- Page Header-->
            <header>
                <h1 class="h3 display">中药方剂知识库</h1>
            </header>
            <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'Formula:index' %}" method="get">
                            <div class="form-group row" style="margin-left: 25%;" >
                                <label class="form-control-label" >方剂名称</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="search-recipe-text"  value="{{ recipe.formulas_name }}" style="vertical-align: middle;">
                                </div>
                                <div class="col-sm-2 " style="text-align: right;">
                                    <button class="btn btn-primary" type="submit">检索</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h2 class="h5">{{ recipe.formulas_name}}</h2>
                            <div>
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist" id="myTabs">
                                    <li role="presentation" ><a href="#home" aria-controls="home" aria-expanded="true" role="tab" data-toggle="tab" id="home-tab">详细信息</a></li>
                                    <li role="presentation" ><a href="#profile" aria-controls="profile" role="tab" aria-expanded="false" data-toggle="tab" id="profile-tab">中药成分</a></li>
                                    <li role="presentation" ><a href="#messages" aria-controls="messages" role="tab" aria-expanded="false" data-toggle="tab" id="messages-tab">相关文献</a></li>
                                </ul>
                                <!-- Tab panes -->
                                <div class="tab-content" id="myTabContent">
                                    <div role="tabpanel" aria-labelledby="home-tab" class="tab-pane active" id="home">
                                        <ul class="list-group">
                                         <li class="list-group-item">【分类】{{recipe.classify }}</li>
                                      </ul>
                                        <ul class="list-group">
                                         <li class="list-group-item">【方义】{{recipe.fangyi }}</li>
                                      </ul>
                                        <ul class="list-group">
                                         <li class="list-group-item">【功用】{{recipe.recfunction }}</li>
                                      </ul>
                                      <ul class="list-group">
                                         <li class="list-group-item">【用法】{{recipe.usage }}</li>
                                      </ul>
                                        <ul class="list-group">
                                         <li class="list-group-item">【加减化裁】{{recipe.plusedreduced }}</li>
                                      </ul>
                                        <ul class="list-group">
                                         <li class="list-group-item">【使用注意】{{recipe.cautioninuse }}</li>
                                      </ul>
                                        <ul class="list-group">
                                         <li class="list-group-item">【配伍特点】{{recipe.compatibilitycha }}</li>
                                      </ul>
                                        <ul class="list-group">
                                         <li class="list-group-item">【歌诀】{{recipe.for_in_verse }}</li>
                                      </ul>
                                    </div>
                                    <div role="tabpanel" aria-labelledby="profile-tab" class="tab-pane fade" id="profile">
                                        <div class="row">
                                            <div class="col-4">
                                                <div class="list-group" id="list-tab" role="tablist">
                                                    {% if reccoms %}
                                                        {% for reccom in reccoms %}
                                                        <a class="list-group-item list-group-item-action " id="list-home-list" data-toggle="list" href="#list{{ reccom.herbs_name }}" role="tab" >{{ reccom.herbs_name }}</a>
                                                        {% endfor %}
                                                    {% else %}
                                                        <div class="row" style="text-align: center"><p style="margin:0 auto;width:200px;"><p>没有查找到对应成分</p></div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="col-8">
                                                <div class="tab-content" id="nav-tabContent">
                                                    {% if reccoms %}
                                                        {% for reccom in reccoms %}
                                                        <div class="tab-pane fade show " id="list{{ reccom.herbs_name }}" role="tabpanel" >
                                                        <br>
{#                                                        优先显示克数#}
                                                            {% if reccom.dosage1 != '0' %}
                                                                <p><div style="color:black">【用量】{{ reccom.dosage1 }}</div></p>
                                                            {% else %}
                                                                <p><div style="color:black">【用量】{{ reccom.dosage2 }}</div></p>
                                                            {% endif %}
                                                        <a href="{% url 'Herb:Search_herb' reccom.herbs_name %}" class="card-link">查看详细信息</a>
                                                        </div>
                                                        {% endfor %}
                                                    {% else %}
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div role="tabpanel" aria-labelledby="messages-tab" class="tab-pane fade" id="messages">
                                        <div class="list-group">
                                            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start ">
                                                <div class="d-flex w-100 justify-content-between">
                                                    <h5 class="mb-1">{{ recipe.provenance }}</h5>
                                                </div>
                                                {% if recipe.imliter != 'null'  %}
                                                <div class="d-flex w-100 justify-content-between">
                                                    <h5 class="mb-1">{{ recipe.imliter }}</h5>
                                                </div>
                                                {% endif %}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

apps/Formula/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}首页{% endblock %}

{% block content %}
<br>
            <div class="container-fluid">
                <!-- Page Header-->
                <header>
                    <h1 class="h3 display">中药方剂知识库</h1>
                </header>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{% url 'Formula:index' %}" method="get">
                                    <div class="form-group row"  style="margin-left: 25%;">
                                        <label class="form-control-label" style=" margin-bottom: 0;padding-top: 0.5rem;">方剂名称</label>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-recipe-text" value="{{ search_text }}" placeholder="示例：四妙勇安汤" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-2 " style="text-align: right;">
                                            <button class="btn btn-primary" type="submit">检索</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
{% if search_text  %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {% if recipe_list %}
                            <h2 class="h5">搜索结果</h2>
                                <div class="list-group">
                                {% for recipe in recipe_list %}
                                  <a href="{% url 'Formula:Search_recipe' recipe %}" class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                      <h5 class="mb-1" >{{ recipe }}</h5>
                                    </div>
                                  </a>
                                {% endfor %}
                                </div>
                                <br>
                                <div class="pagination row">
                                    <div class="m-auto">
                                        <span class="step-links">
                                            <!-- 如果不是第一页，则显示上翻按钮 -->
                                            {% if recipe_list.has_previous %}
                                                <a href="?search-recipe-text={{ search_text }}&page=1" class="btn btn-success">
                                                    &laquo; 1
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.previous_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.previous_page_number }}
                                                </a>
                                            {% endif %}

                                            <!-- 当前页面 -->
                                            <span class="current btn btn-success btn-lg">
                                                {{ recipe_list.number }}
                                            </span>

                                            <!-- 如果不是最末页，则显示下翻按钮 -->
                                            {% if recipe_list.has_next %}
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.next_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.next_page_number }}
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.paginator.num_pages }}"
                                                   class="btn btn-success"
                                                >
                                                    {{ recipe_list.paginator.num_pages }} &raquo;
                                                </a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <h2 class="card-title">未找到相关结果</h2>
                                <br>
                                <p class="card-subtitle mb-2 text-muted">您可以:</p>
                                <p class="card-text">1.检查检索词是否有误或者过于复杂</p>
                                <p class="card-text">2.在其他栏目中搜索“{{ search_text }}”</p>
                                <a href="{% url 'Formula:index' %}" class="card-link">返回</a>
                             {% endif %}
                        </div>
                    </div>
                </div>
        </div>
{% endif %}
    </div>
{% endblock %}