Knowledge_Graph/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #图谱展示
    path('Graphapp/', include(('apps.Graphapp.urls',"Graphapp"),namespace='Graphapp')),
    #成分对比分析
    path('Analysis/', include(('apps.Analysis.urls',"Analysis"),namespace='Analysis')),
    #方剂知识库
    path('Formula/', include(('apps.Formula.urls',"Formula"),namespace='Formula')),
    #药材知识库
    path('Herb/', include(('apps.Herb.urls',"Herb"),namespace='Herb')),
    #组分知识库
    path('Ingredients/', include(('apps.Ingredients.urls',"Ingredients"),namespace='Ingredients')),
    #靶标知识库
    path('Target/', include(('apps.Target.urls',"Target"),namespace='Target')),
    #方剂配伍
    path('Combination/', include(('apps.Combination.urls',"Combination"),namespace='Combination'))
  ]

apps/Analysis/urls.py
from django.urls import path

from apps.Analysis import views

urlpatterns = [
#查询分析
 path('Analysisindex/', views.Analysisindex, name='Analysisindex'),
 path('Analysis/<str:name>/', views.Analysis, name='Analysis'),

 path('FAnalyindex/', views.FAnalyindex, name='FAnalyindex'),
 path('FAnalysis/<str:name>/', views.FAnalysis, name='FAnalysis')
]

apps/Ingredients/urls.py
from django.urls import path

from apps.Ingredients import views

urlpatterns = [
         #组分
 path('Comindex/', views.Comindex, name='Comindex'),
 path('Search_com/<str:name>/', views.Search_com, name='Search_com'),
         ]

apps/Target/urls.py
from django.urls import path

from apps.Target import views

urlpatterns = [
 path('Targetindex/', views.Targetindex, name='Targetindex'),
 path('Search_target/<str:name>/', views.Search_target, name='Search_target'),
               ]

apps/Analysis/models.py
from django.db import models

# Create your models here.

apps/Analysis/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
import json
from apps.Graphapp.models import Herbs,Formulas,Forcom,Herbsmol,Tamol

#药材对比分析
def Analysisindex(request):
    search_text1=request.GET.get('search-text1')
    search_text2=request.GET.get('search-text2')
    if not (search_text1 or search_text2):
        return render(request, 'Analysisindex.html')
    #模糊搜索
    herbs1=Herbs.objects.filter(herbs_name__contains=search_text1).values_list('herbs_name',flat=True)
    herbs2=Herbs.objects.filter(herbs_name__contains=search_text2).values_list('herbs_name',flat=True)
    #没有找到
    if not (herbs1 or herbs2):
        return render(request, 'Analysisindex.html', {'search_text1':search_text1, 'search_text2':search_text2})
    else:
        if not herbs1:
            return render(request, 'Analysisindex.html', {'search_text1':search_text1})
        else:
            if not herbs2:
                return render(request, 'Analysisindex.html', {'search_text2':search_text2})
    #组合查询结果
    herbs=[]
    dict={}
    for herb1 in herbs1:
        for herb2 in herbs2:
            if herb1 != herb2:
                if herb1>herb2:
                    herb_item=herb1 +'   '+ herb2
                else:
                    herb_item=herb2 +'   '+ herb1
                dict[herb_item]=True
    for key in dict:
        herbs.append(key)
    p = Paginator(herbs,10)
    page = request.GET.get('page',1)
    herb_list = p.get_page(page)
    return render(request, 'Analysisindex.html', {'search_text1':search_text1, 'search_text2':search_text2, 'herb_list':herb_list})
def Analysis(request,name):
    #拆分name
    herb=name.split('   ')
    mols1=Herbsmol.objects.filter(herbs_name=herb[0]).values_list('molecular_name',flat=True)
    mols2=Herbsmol.objects.filter(herbs_name=herb[1]).values_list('molecular_name',flat=True)
    #求交
    mol=set(mols1)&set(mols2)
    tar1=[]
    tar2=[]
    for mol1 in mols1:
        for i in Tamol.objects.filter(molecular_name=mol1).values_list('tg_name',flat=True):
            tar1.append(i)
    for mol2 in mols2:
        for i in Tamol.objects.filter(molecular_name=mol2).values_list('tg_name',flat=True):
            tar2.append(i)
    tar = set(tar1)&set(tar2)
    return render(request, 'Analysis.html', {'mol':mol, 'tar':tar, 'name':name, 'herb1':herb[0], 'herb2':herb[1]})
#方剂对比分析
def FAnalyindex(request):
    search_text1=request.GET.get('search-text1')
    search_text2=request.GET.get('search-text2')
    if not (search_text1 or search_text2):
        return render(request, 'FAnalyindex.html')
    #模糊搜索
    formulas1=Formulas.objects.filter(formulas_name__contains=search_text1,mark=1).values_list('formulas_name',flat=True)
    formulas2=Formulas.objects.filter(formulas_name__contains=search_text2,mark=1).values_list('formulas_name',flat=True)
    #没有找到
    if not (formulas1 or formulas2):
        return render(request, 'FAnalyindex.html', {'search_text1':search_text1, 'search_text2':search_text2})
    else:
        if not formulas1:
            return render(request, 'FAnalyindex.html', {'search_text1':search_text1})
        else:
            if not formulas2:
                return render(request, 'FAnalyindex.html', {'search_text2':search_text2})
    #组合查询结果
    formulas=[]
    dict={}
    for formula1 in formulas1:
        for formula2 in formulas2:
            if formula1 != formula2:
                if formula1>formula2:
                    formula_item=formula1 +'   '+ formula2
                else:
                    formula_item=formula2 +'   '+ formula1
                dict[formula_item]=True
    for key in dict:
        formulas.append(key)
    p = Paginator(formulas,10)
    page = request.GET.get('page',1)
    formula_list = p.get_page(page)
    return render(request, 'FAnalyindex.html', {'search_text1':search_text1, 'search_text2':search_text2, 'formula_list':formula_list})
def FAnalysis(request,name):
    #拆分name
    formula=name.split('   ')
    nodes = []
    links = []
    nodes.append({'id': formula[0], 'class': 'recipe', 'group': 0, 'size': 20})
    nodes.append({'id': formula[1], 'class': 'recipe', 'group': 0, 'size': 20})
    formula1=Formulas.objects.filter(formulas_name=formula[0],mark=1).values_list('formulas_no',flat=True)
    formula2=Formulas.objects.filter(formulas_name=formula[1],mark=1).values_list('formulas_no',flat=True)
    herbs1=Forcom.objects.filter(formulas_no=formula1[0],mark=1).values_list('herbs_name',flat=True)
    herbs2=Forcom.objects.filter(formulas_no=formula2[0],mark=1).values_list('herbs_name',flat=True)
    mols1=[]
    mols2=[]
    for herb1 in herbs1:
        nodes.append({'id': herb1, 'class': 'herb', 'group': 1, 'size': 15})
        links.append({'source': formula[0], 'target': herb1, 'value': 3})
        for i in Herbsmol.objects.filter(herbs_name=herb1).values_list('molecular_name',flat=True):
            mols1.append(i)
    for herb2 in herbs2:
        nodes.append({'id': herb2, 'class': 'herb', 'group': 1, 'size': 15})
        links.append({'source': formula[1], 'target': herb2, 'value': 3})
        for i in Herbsmol.objects.filter(herbs_name=herb2).values_list('molecular_name',flat=True):
            mols2.append(i)
    #去重
    node=[]
    for i in nodes:
        if i not in node:
            node.append(i)
    nodes=node
    #求交
    mol=set(mols1)&set(mols2)
    tar1=[]
    tar2=[]
    for mol1 in mols1:
        for i in Tamol.objects.filter(molecular_name=mol1).values_list('tg_name',flat=True):
            tar1.append(i)
    for mol2 in mols2:
        for i in Tamol.objects.filter(molecular_name=mol2).values_list('tg_name',flat=True):
            tar2.append(i)
    tar = set(tar1)&set(tar2)
    #添加共同靶标
    for tar_item in tar:
        nodes.append({'id': tar_item, 'class': 'Target', 'group': 3, 'size': 10})
        for i in Tamol.objects.filter(tg_name=tar_item).values_list('molecular_name',flat=True):
            for j in Herbsmol.objects.filter(molecular_name=i).values_list('herbs_name',flat=True):
                if (j in (herbs1 or herbs2)):
                    links.append({'source': j, 'target': tar_item, 'value': 3})
     #添加共同组分
    for mol_item in mol:
        nodes.append({'id': mol_item, 'class': 'Molecule', 'group': 2, 'size': 10})
        for i in Herbsmol.objects.filter(molecular_name=mol_item).values_list('herbs_name',flat=True):
             if (i in (herbs1 or herbs2)):
                links.append({'source': i, 'target': mol_item, 'value': 3})
    #组合成json字符串
    arg=json.dumps({'nodes': nodes, 'links': links})
    return render(request, 'FAnalysis.html', {'mol':mol, 'tar':tar, 'name':name, 'formula1':formula[0], 'formula2':formula[1], 'herbs1':herbs1, 'herbs2':herbs2,'arg':arg})

apps/Analysis/templates/Analysis.html
{% extends 'base.html' %}
{% load static %}
{% block title %}药材成分对比分析{% endblock %}

{% block content %}
    <!-- Counts Section -->
    <br>
        <div class="container-fluid">
            <!-- Page Header-->
            <header>
                <h1 class="h3 display">药材成分对比分析</h1>
            </header>
            <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'Analysis:Analysisindex' %}" method="get">
                            <div class="form-group row" style="margin-left: 15%;" >
                                <label class="form-control-label" >药材名称</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="search-text1"  value="{{ herb1 }}" style="vertical-align: middle;">
                                </div>
                                <div class="col-sm-4">
                                     <input type="text" class="form-control" name="search-text2" value="{{ herb2 }}"  style="vertical-align: middle;">
                                </div>
                                <div class="col-sm-2 " style="text-align: right;">
                                    <button class="btn btn-primary" type="submit">检索</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h2 class="h5">{{ name }}</h2>
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist" id="myTabs">
                                    <li role="presentation" ><a href="#com" aria-controls="com" role="tab" aria-expanded="true" data-toggle="tab" id="com-tab">共同组分分子</a></li>
                                    <li role="presentation" ><a href="#gene" aria-controls="gene" role="tab" aria-expanded="false" data-toggle="tab" id="gene-tab">共同靶标</a></li>
                                </ul>
                                <!-- Tab panes -->
                                <div class="tab-content" id="myTabContent">
                                    <div role="tabpanel" aria-labelledby="profile-tab" class="tab-pane active" id="com">
                                            <div class="list-group" id="list-tab" role="tablist">
                                                    {% if mol %}
                                                        {% for component in mol %}
                                                         <a href="{% url 'Ingredients:Search_com' component %}" class="list-group-item list-group-item-action flex-column align-items-start">
                                                            <div class="d-flex w-100 justify-content-between">
                                                              <h5 class="mb-1" >{{ component }}</h5>
                                                            </div>
                                                            </a>
                                                        {% endfor %}
                                                    {% else %}
                                                        <br>
                                                        <div class="row" style="text-align: center"><p style="margin:0 auto;width:200px;">没有查找到共同组分分子</p></div>
                                                    {% endif %}
                                            </div>
                                        </div>
                                    <div role="tabpanel" aria-labelledby="messages-tab" class="tab-pane fade" id="gene">
                                                <div class="list-group" id="list-tab" role="tablist">
                                                    {% if tar %}
                                                        {% for target in tar %}
                                                        <div class="list-group">
                                                        <a href="{% url 'Target:Search_target' target %}" class="list-group-item list-group-item-action flex-column align-items-start ">
                                                            <div class="d-flex w-100 justify-content-between">
                                                              <h5 class="mb-1" >{{ target }}</h5>
                                                            </div>
                                                        </a>
                                                        </div>
                                                        {% endfor %}
                                                    {% else %}
                                                        <br>
                                                        <div class="row" style="text-align: center"><p style="margin:0 auto;width:200px;">没有查找到共同靶标</p></div>
                                                    {% endif %}
                                                </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
{% endblock %}

apps/Analysis/templates/Analysisindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %}药材成分对比分析{% endblock %}

{% block content %}
<br>
            <div class="container-fluid">
                <!-- Page Header-->
                <header>
                    <h1 class="h3 display">药材成分对比分析</h1>
                </header>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{% url 'Analysis:Analysisindex' %}" method="get">
                                    <div class="form-group row" style="margin-left: 15%;" >
                                        <label class="form-control-label" >药材名称</label>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-text1" value="{{ search_text1 }}" placeholder="示例：海藻" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-text2" value="{{ search_text2 }}" placeholder="示例：附子" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-2 " style="text-align: right;">
                                            <button class="btn btn-primary" type="submit">检索</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

    {% if search_text1 or search_text2 %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {% if herb_list %}
                            <h2 class="h5">搜索结果</h2>
                            {% for herb in herb_list %}
                                <div class="list-group">
                                  <a href="{% url 'Analysis:Analysis' herb %} " class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                      <h5 class="mb-1" >{{ herb }}</h5>
                                    </div>
                                  </a>
                                </div>
                                {% endfor %}
                                <br>
                                <div class="pagination row">
                                    <div class="m-auto">
                                        <span class="step-links">
                                            <!-- 如果不是第一页，则显示上翻按钮 -->
                                            {% if herb_list.has_previous %}
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page=1" class="btn btn-success">
                                                    &laquo; 1
                                                </a>
                                                <span>...</span>
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ herb_list.previous_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ herb_list.previous_page_number }}
                                                </a>
                                            {% endif %}
                                            <!-- 当前页面 -->
                                            <span class="current btn btn-success btn-lg">
                                                {{ herb_list.number }}
                                            </span>

                                            <!-- 如果不是最末页，则显示下翻按钮 -->
                                            {% if herb_list.has_next %}
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ herb_list.next_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ herb_list.next_page_number }}
                                                </a>
                                                <span>...</span>
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ herb_list.paginator.num_pages }}"
                                                   class="btn btn-success"
                                                >
                                                    {{ herb_list.paginator.num_pages }} &raquo;
                                                </a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <h2 class="card-title">未找到相关结果</h2>
                                <br>
                                <p class="card-subtitle mb-2 text-muted">您可以:</p>
                                <p class="card-text">1.检查检索词是否有误或者过于复杂</p>
                                {% if search_text1 and search_text2 %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text1 }}”和“{{ search_text2 }}”</p>
                                {% elif search_text1 %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text1 }}”</p>
                                {% else %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text2 }}”</p>
                                {% endif %}
                                    <a href="{% url 'Analysis:Analysisindex' %}" class="card-link">返回</a>
                             {% endif %}
                        </div>
                    </div>
                </div>
        </div>
{% endif %}
    </div>
{% endblock %}

apps/Analysis/templates/FAnalyindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %}方剂成分对比分析{% endblock %}

{% block content %}
<br>
            <div class="container-fluid">
                <!-- Page Header-->
                <header>
                    <h1 class="h3 display">方剂成分对比分析</h1>
                </header>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{% url 'Analysis:FAnalyindex' %}" method="get">
                                    <div class="form-group row" style="margin-left: 15%;" >
                                        <label class="form-control-label" >方剂名称</label>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-text1" value="{{ search_text1 }}" placeholder="示例：软坚清脉颗粒" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-text2" value="{{ search_text2 }}" placeholder="示例：软坚清脉方" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-2 " style="text-align: right;">
                                            <button class="btn btn-primary" type="submit">检索</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
    {% if search_text1 or search_text2 %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {% if formula_list %}
                            <h2 class="h5">搜索结果</h2>
                                <div class="list-group">
                                {% for formula in formula_list %}
                                  <a href="{% url 'Analysis:FAnalysis' formula %} " class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                      <h5 class="mb-1" >{{ formula }}</h5>
                                    </div>
                                  </a>
                                {% endfor %}
                                </div>
                                <br>
                                <div class="pagination row">
                                    <div class="m-auto">
                                        <span class="step-links">
                                            <!-- 如果不是第一页，则显示上翻按钮 -->
                                            {% if formula_list.has_previous %}
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page=1" class="btn btn-success">
                                                    &laquo; 1
                                                </a>
                                                <span>...</span>
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ formula_list.previous_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ formula_list.previous_page_number }}
                                                </a>
                                            {% endif %}
                                            <!-- 当前页面 -->
                                            <span class="current btn btn-success btn-lg">
                                                {{ formula_list.number }}
                                            </span>

                                            <!-- 如果不是最末页，则显示下翻按钮 -->
                                            {% if formula_list.has_next %}
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ formula_list.next_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ formula_list.next_page_number }}
                                                </a>
                                                <span>...</span>
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ formula_list.paginator.num_pages }}"
                                                   class="btn btn-success"
                                                >
                                                    {{ formula_list.paginator.num_pages }} &raquo;
                                                </a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <h2 class="card-title">未找到相关结果</h2>
                                <br>
                                <p class="card-subtitle mb-2 text-muted">您可以:</p>
                                <p class="card-text">1.检查检索词是否有误或者过于复杂</p>
                                {% if search_text1 and search_text2 %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text1 }}”和“{{ search_text2 }}”</p>
                                {% elif search_text1 %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text1 }}”</p>
                                {% else %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text2 }}”</p>
                                {% endif %}
                                    <a href="{% url 'Analysis:FAnalyindex' %}" class="card-link">返回</a>
                             {% endif %}
                        </div>
                    </div>
                </div>
        </div>
{% endif %}
    </div>
{% endblock %}