Knowledge_Graph/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #图谱展示
    path('Graphapp/', include(('apps.Graphapp.urls',"Graphapp"),namespace='Graphapp')),
    #成分对比分析
    path('Analysis/', include(('apps.Analysis.urls',"Analysis"),namespace='Analysis')),
    #方剂知识库
    path('Formula/', include(('apps.Formula.urls',"Formula"),namespace='Formula')),
    #药材知识库
    path('Herb/', include(('apps.Herb.urls',"Herb"),namespace='Herb')),
    #组分知识库
    path('Ingredients/', include(('apps.Ingredients.urls',"Ingredients"),namespace='Ingredients')),
    #靶标知识库
    path('Target/', include(('apps.Target.urls',"Target"),namespace='Target')),
    #方剂配伍
    path('Combination/', include(('apps.Combination.urls',"Combination"),namespace='Combination'))
  ]

apps/Combination/urls.py
from django.urls import path

from apps.Combination import views

urlpatterns = [
 path('FComindex/', views.FComindex, name='FComindex'),
 path('FCom/<str:name>/', views.FCom, name='FCom'),
 # path('FComnew/', views.FComnew, name='FComnew'),
 # path('FCom/<str:name>/form', views.FComnew, name='FComnew'),
 ]

apps/Combination/models.py
from django.db import models

# Create your models here.

apps/Combination/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Max
from apps.Graphapp.models import Formulas,Forcom
import uuid
import json

# Create your views here.

#加减化裁界面
def FCom(request,name):
    recipe=Formulas.objects.filter(formulas_name=name)
    reccoms=Forcom.objects.filter(formulas_no=recipe[0].formulas_no).values_list('herbs_name',flat=True)
    if request.POST.get("save") == "add":
        try:
            #计算新方剂编号
            #marker=2:自建方剂
            formulas_name=request.POST.get("formulas_name")
            formulas_no=uuid.uuid5(uuid.NAMESPACE_DNS, formulas_name)
            print(formulas_no)
            count = Formulas.objects.filter(formulas_name=formulas_name).count()
            arg=json.dumps({'name': count})
            if count>0:
                return render(request, 'FCom.html', {'reccoms':reccoms, 'recipe':recipe[0],'arg':arg})
            Formulas.objects.create(
                        formulas_no=formulas_no,
                        formulas_name=formulas_name,
                        mark=2,
                    )
            for i in range(1,len(request.POST)-2):
                i=str(i)
                print(request.POST.get(i))
                if request.POST.get(i):
                    herbs_name=request.POST.get(i)
                    forcom_no=uuid.uuid5(uuid.NAMESPACE_DNS, herbs_name)
                    print(forcom_no)
                    Forcom.objects.create(
                              forcom_no=forcom_no,
                              formulas_no=formulas_no,
                              herbs_name=request.POST.get(i),
                              mark=2,
                          )
            message = "操作成功！"
        except Exception as e:
            print(str(e))
            message = "操作失败:请尝试重新填写！"
        return render(request, 'FCom.html', {'reccoms':reccoms, 'recipe':recipe[0],'message':message,'arg':arg})
    return render(request, 'FCom.html', {'reccoms':reccoms, 'recipe':recipe[0]})
def FComindex(request):
    search_text=request.GET.get('search-recipe-text')
    if not search_text:
        return render(request, 'FComindex.html')
    #TODO: 搜索拉丁文名
    #模糊搜索
    recipes=Formulas.objects.filter(formulas_name__contains=search_text)
    #搜索不到
    if not recipes:
        return render(request, 'FComindex.html', {'search_text':search_text})
    p = Paginator(recipes,10)   #分页，10个一页
    # 获取 url 中的页码
    page = request.GET.get('page',1)
    # 将导航对象相应的页码内容返回给 articles
    recipe_list = p.get_page(page)
    return render(request, 'FComindex.html', {'search_text':search_text, 'recipe_list': recipe_list})

apps/Combination/templates/FCom.html
{% extends 'base.html' %}
{% load static %}
{% block title %}方剂配伍(加减化裁){% endblock %}

{% block content %}
    <br>
        <div class="container-fluid">
            <!-- Page Header-->
            <header>
                <h1 class="h3 display">方剂配伍(加减化裁)</h1>
            </header>
            <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'Combination:FComindex' %}" method="get">
                            <div class="form-group row" style="margin-left: 25%;" >
                                <label class="form-control-label" >方剂名称</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="search-recipe-text"  value="{{ recipe.formulas_name }}" style="vertical-align: middle;">
                                </div>
                                <div class="col-sm-2 " style="text-align: right;">
                                    <button class="btn btn-primary" type="submit">检索</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
                {% if message %} {% ifequal message "操作成功！" %}
    <div class="alert alert-warning alert-dismissible text-center" role="alert">
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>{{ message }}</strong>
    </div>
    {% else %}
    <div class="alert alert-danger alert-dismissible text-center" role="alert">
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>{{ message }}</strong>
    </div>
    {% endifequal %} {% endif %}
        </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h2 class="h5">{{ recipe.formulas_name}}</h2>
                        {% if reccoms %}
                            <ul class="list-group">
                              {% for reccom in reccoms %}
                                  <li class="list-group-item">{{ reccom }}
                                  </li>
                              {% endfor %}
                            </ul>
                        {% else %}
                            <div class="row" style="text-align: center"><p style="margin:0 auto;width:200px;">没有查找到中药成分</p></div>
                            <br>
                        {% endif %}
                        <br>
                         <div class="col-sm-6 offset-sm-5">
                         <button
                        class="btn btn-primary"
                        data-toggle="modal"
                        data-target="#Modalnew"
                      >
                        创建新方剂
                      </button>
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{#    模态框#}
    <div
  class="modal fade"
  id="Modalnew"
  tabindex="-1"
  role="dialog"
  style="display: none;"
  aria-labelledby="myModalLabel"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModal2Label" style="text-align: center;">
          创建新方剂
        </h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal" action="{% url 'Combination:FCom' recipe.formulas_name %}" method="POST">
         {% csrf_token %}
        <div class="content">
          <div class="form-group row" id="formulas_name">
            <label class="col-sm-3 form-control-label">新方剂名称</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" name="formulas_name" />
          </div>
              </div>
         <br>
            {% for forcom in reccoms %}
             <div class="line"></div>
            <div class="form-group row">
            <label class="col-sm-3 form-control-label">组分</label>
                <div class="col-sm-8">
                    <input
                            type="text"
                            name="{{forloop.counter}}"
                            class="form-control"
                            value="{{ forcom }}"
                    />
                </div>
            </div>
                <br>
            {% endfor %}
        </div>
          <div class="modal-footer">
              <button  class="btn btn-info col-sm-2 offset-sm-6" type="reset" >
              重置
            </button>
              <button  class="btn btn-primary col-sm-3 offset-sm-6" id="create" type="button" >
              添加新组分
            </button>
            <button
              type="button"
              class="btn btn-default col-sm-2 offset-sm-4"
              data-dismiss="modal"
              id="dismiss"
            >
              取消
            </button>
            <button type="submit" class="btn btn-primary col-sm-4 offset-sm-6" name="save" value="add">
              创建为新方剂
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
    <script type="text/javascript">
      $(document).ready(function() {
          $("#create").on("click", function () {   //单击事件
              console.log(1)
              $(".content").append('<div class="line"></div> <div class="form-group row"> <label class="col-sm-3 form-control-label">组分</label> <div class="col-sm-8"> <input type="text" name="amtreceivable" class="form-control" /> </div> </div> <br>');//在按钮的内部的下方添加一行
          });
          if ({{ arg | safe }}["name"]>0) {//名称重复时 模态框保持开启
              $("#Modalnew").attr("style","display: block; padding-right: 17px;")
                      .attr("class","modal fade show")
                      .attr("aria-modal","true");
              $("body").attr("class","modal-open")
                      .attr("style","padding-right: 17px;");
              $("#formulas_name").append('<div class="row" style="text-align: center;"><p style="margin:0 auto;width:200px;color:orange">方剂名称已存在！</p></div>');
              $("#dismiss").on("click", function () {   //关闭模态框
                $("body").attr("class","")
                      .attr("style","");
                $("#Modalnew").attr("style","display: none")
                      .attr("class","modal fade")
                      .attr("aria-modal","false");
{#                var key="name";#}
{#                delete{{ arg|safe }}[key];#}
{#                console.log({{ arg|safe }})#}
          });
          };
      });
    </script>
{% endblock %}

apps/Combination/templates/FComindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %}方剂配伍(加减化裁){% endblock %}

{% block content %}
<br>
            <div class="container-fluid">
                <!-- Page Header-->
                <header>
                    <h1 class="h3 display">方剂配伍(加减化裁)</h1>
                </header>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{% url 'Combination:FComindex' %}" method="get">
                                    <div class="form-group row"  style="margin-left: 25%;">
                                        <label class="form-control-label" style=" margin-bottom: 0;padding-top: 0.5rem;">方剂名称</label>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-recipe-text" value="{{ search_text }}" placeholder="示例：四妙勇安汤" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-2 " style="text-align: right;">
                                            <button class="btn btn-primary" type="submit">检索</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
{% if search_text  %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {% if recipe_list %}
                            <h2 class="h5">搜索结果</h2>
                                <div class="list-group">
                            {% for recipe in recipe_list %}
                                  <a href="{% url 'Combination:FCom' recipe.formulas_name %} " class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                      <h5 class="mb-1" >{{ recipe.formulas_name }}</h5>
                                    </div>
                                  </a>
                                {% endfor %}
                                </div>
                                <br>
                                <div class="pagination row">
                                    <div class="m-auto">
                                        <span class="step-links">
                                            <!-- 如果不是第一页，则显示上翻按钮 -->
                                            {% if recipe_list.has_previous %}
                                                <a href="?search-recipe-text={{ search_text }}&page=1" class="btn btn-success">
                                                    &laquo; 1
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.previous_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.previous_page_number }}
                                                </a>
                                            {% endif %}

                                            <!-- 当前页面 -->
                                            <span class="current btn btn-success btn-lg">
                                                {{ recipe_list.number }}
                                            </span>

                                            <!-- 如果不是最末页，则显示下翻按钮 -->
                                            {% if recipe_list.has_next %}
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.next_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.next_page_number }}
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipe-text={{ search_text }}&page={{ recipe_list.paginator.num_pages }}"
                                                   class="btn btn-success"
                                                >
                                                    {{ recipe_list.paginator.num_pages }} &raquo;
                                                </a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <h2 class="card-title">未找到相关结果</h2>
                                <br>
                                <p class="card-subtitle mb-2 text-muted">您可以:</p>
                                <p class="card-text">1.检查检索词是否有误或者过于复杂</p>
                                <p class="card-text">2.在其他栏目中搜索“{{ search_text }}”</p>
                                <a href="{% url 'Combination:FComindex' %}" class="card-link">返回</a>
                             {% endif %}
                        </div>
                    </div>
                </div>
        </div>
{% endif %}
    </div>
{% endblock %}