Knowledge_Graph/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #图谱展示
    path('Graphapp/', include(('apps.Graphapp.urls',"Graphapp"),namespace='Graphapp')),
    #成分对比分析
    path('Analysis/', include(('apps.Analysis.urls',"Analysis"),namespace='Analysis')),
    #方剂知识库
    path('Formula/', include(('apps.Formula.urls',"Formula"),namespace='Formula')),
    #药材知识库
    path('Herb/', include(('apps.Herb.urls',"Herb"),namespace='Herb')),
    #组分知识库
    path('Ingredients/', include(('apps.Ingredients.urls',"Ingredients"),namespace='Ingredients')),
    #靶标知识库
    path('Target/', include(('apps.Target.urls',"Target"),namespace='Target')),
    #方剂配伍
    path('Combination/', include(('apps.Combination.urls',"Combination"),namespace='Combination'))
  ]

apps/Analysis/urls.py
from django.urls import path

from apps.Analysis import views

urlpatterns = [
#查询分析
 path('Analysisindex/', views.Analysisindex, name='Analysisindex'),
 path('Analysis/<str:name>/', views.Analysis, name='Analysis'),

 path('FAnalyindex/', views.FAnalyindex, name='FAnalyindex'),
 path('FAnalysis/<str:name>/', views.FAnalysis, name='FAnalysis')
]

apps/Formula/urls.py
from django.urls import path
from apps.Formula import views


urlpatterns = [
 #方剂信息展示页面
 path('Search_recipe/<str:name>', views.Search_recipe, name='Search_recipe'),
 path('index/', views.index, name='index'),
  #不良反应
 path('ADRindex/', views.ADRindex, name='ADRindex'),
 path('ADR/<str:name>', views.ADR, name='ADR')
 ]

apps/Graphapp/urls.py
from django.urls import path

from apps.Graphapp import views

urlpatterns = [
 #方剂KG搜索页面
 path('Recipehcindex/', views.Recipehcindex, name='Recipehcindex'),
 path('Recipehmiindex/', views.Recipehmiindex, name='Recipehmiindex'),
 #方剂KG展示
 path('RecipehcKG/<str:name>/', views.RecipehcKG, name='RecipehcKG'),
 path('RecipehmiKG/<str:name>/', views.RecipehmiKG, name='RecipehmiKG'),


 path('Predictindex/', views.Predictindex, name='Predictindex'),
 path('PredictKG/<str:name>/', views.PredictKG, name='PredictKG'),
]

apps/Herb/urls.py
from django.urls import path

from apps.Herb import views

urlpatterns = [
        #药材信息展示页面
 path('herbindex/', views.herbindex, name='herbindex'),
 path('Search_herb/<str:name>/', views.Search_herb, name='Search_herb')
 ]

apps/Target/urls.py
from django.urls import path

from apps.Target import views

urlpatterns = [
 path('Targetindex/', views.Targetindex, name='Targetindex'),
 path('Search_target/<str:name>/', views.Search_target, name='Search_target'),
               ]

apps/Graphapp/views.py
import json

from django.core.paginator import Paginator
from django.shortcuts import render

from apps.Graphapp.models import Herbs,Formulas,Target,Forcom,Herbsmol,Tamol

#药材组分知识图谱
def Recipehcindex(request):
    search_text=request.GET.get('search-recipehcKG-text')
    if not search_text:
        return render(request,'Recipehcindex.html')
    #TODO: 搜索拉丁文名
    #模糊搜索
    recipes=Formulas.objects.filter(formulas_name__contains=search_text,mark=1).values_list('formulas_name',flat=True)
    #搜索不到
    if not recipes:
        return render(request, 'Recipehcindex.html', {'search_text':search_text})
    p = Paginator(recipes,10)   #分页，10个一页
    # 获取 url 中的页码
    page = request.GET.get('page',1)
    # 将导航对象相应的页码内容返回给 articles
    recipe_list = p.get_page(page)
    return render(request, 'Recipehcindex.html', {'search_text':search_text,'recipe_list':recipe_list})
def RecipehcKG(request,name):
        recipe=Formulas.objects.filter(formulas_name=name,mark=1)
        nodes = []
        links = []
        #TODO:查询优化
        #1 查询该方剂对应所有药材 source：方剂 target：药材 node：药材
        nodes.append({'id': recipe[0].formulas_name, 'class': 'recipe', 'group': 0, 'size': 20})
        herbs=Forcom.objects.filter(formulas_no=recipe[0].formulas_no,mark=1).values_list('herbs_name',flat=True)
        #2 查询每种药材对应组分分子 source：药材 target：分子
        for herb in herbs:
            nodes.append({'id': herb, 'class': 'herb', 'group': 1, 'size': 15})
            links.append({'source': recipe[0].formulas_name, 'target': herb, 'value': 3})
            molecules=Herbsmol.objects.filter(herbs_name=herb).values_list('molecular_name',flat=True)
            for molecule in molecules:
                 nodes.append({'id': molecule, 'class': 'Molecule', 'group': 2, 'size': 10})
                 links.append({'source': herb, 'target': molecule, 'value': 3})
        #去重
        node=[]
        for i in nodes:
            if i not in node:
                node.append(i)
        #组合成json字符串
        arg=json.dumps({'nodes': node, 'links': links})
        return render(request,'RecipehcKG.html',{'arg':arg,'recipe_mame':name})
#药材靶标疾病知识图谱
def RecipehmiKG(request,name):
        recipe=Formulas.objects.filter(formulas_name=name,mark=1)
        nodes = []
        links = []
        #1 查询该方剂对应所有药材 source：方剂 target：药材 node：药材
        nodes.append({'id': recipe[0].formulas_name, 'class': 'recipe', 'group': 0, 'size': 20})
        herbs=Forcom.objects.filter(formulas_no=recipe[0].formulas_no,mark=1).values_list('herbs_name',flat=True)
        #2 查询每个药材对应靶标source：药材 target：靶标
        for herb in herbs:
            nodes.append({'id': herb, 'class': 'herb', 'group': 1, 'size': 15})
            links.append({'source': recipe[0].formulas_name, 'target': herb, 'value': 3})
            molecules=Herbsmol.objects.filter(herbs_name=herb).values_list('molecular_name',flat=True)
            for molecule in molecules:
                targets=Tamol.objects.filter(molecular_name=molecule).values_list('tg_name',flat=True)
                for target in targets:
                    nodes.append({'id': target, 'class': 'Target', 'group': 2, 'size': 10,'activesize':15})
                    links.append({'source': herb, 'target': target, 'value': 3})
                 #3 查询每个靶标对应疾病 source：靶标 target：疾病
                    disease=Target.objects.filter(target_name=target).values_list('diseasesName',flat=True)
                    if disease:
                        diseaseNames=disease[0].split(';')
                        for diseaseName in diseaseNames:
                            nodes.append({'id': diseaseName, 'class': 'Molecule', 'group': 3, 'size': 8,'activesize':13})
                            links.append({'source': target, 'target': diseaseName, 'value': 3})
        #去重
        node=[]
        for i in nodes:
            if i not in node:
                node.append(i)
        #组合成json字符串
        arg=json.dumps({'nodes': node, 'links': links})
        return render(request,'RecipehmiKG.html',{'arg':arg,'recipe_mame':name})
def Recipehmiindex(request):
    search_text=request.GET.get('search-recipehmiKG-text')
    if not search_text:
        return render(request,'Recipehmiindex.html')
    #TODO: 搜索拉丁文名
    #模糊搜索
    recipes=Formulas.objects.filter(formulas_name__contains=search_text,mark=1).values_list('formulas_name',flat=True)
    #搜索不到
    if not recipes:
        return render(request, 'Recipehmiindex.html', {'search_text':search_text})
    p = Paginator(recipes,10)   #分页，10个一页
    # 获取 url 中的页码
    page = request.GET.get('page',1)
    # 将导航对象相应的页码内容返回给 articles
    recipe_list = p.get_page(page)
    return render(request, 'Recipehmiindex.html', {'search_text':search_text,'recipe_list':recipe_list})
#药对配伍界面
def Predictindex(request):
    search_text1=request.GET.get('search-text1')
    search_text2=request.GET.get('search-text2')
    if not (search_text1 or search_text2):
        return render(request, 'Predictindex.html')
    #模糊搜索
    herbs1=Herbs.objects.filter(herbs_name__contains=search_text1).values_list('herbs_name',flat=True)
    herbs2=Herbs.objects.filter(herbs_name__contains=search_text2).values_list('herbs_name',flat=True)
    #没有找到
    if not (herbs1 or herbs2):
        return render(request, 'Predictindex.html', {'search_text1':search_text1,'search_text2':search_text2})
    else:
        if not herbs1:
            return render(request, 'Predictindex.html', {'search_text1':search_text1})
        else:
            if not herbs2:
                return render(request, 'Predictindex.html', {'search_text2':search_text2})
    #组合查询结果
    herbs=[]
    dict={}
    for herb1 in herbs1:
        for herb2 in herbs2:
            if herb1 != herb2:
                if herb1>herb2:
                    herb_item=herb1 +'   '+ herb2
                else:
                    herb_item=herb2 +'   '+ herb1
                dict[herb_item]=True
    for key in dict:
        herbs.append(key)
    p = Paginator(herbs,10)
    page = request.GET.get('page',1)
    herb_list = p.get_page(page)
    return render(request, 'Predictindex.html', {'search_text1':search_text1,'search_text2':search_text2, 'herb_list':herb_list})
def PredictKG(request,name):
    herbs=name.split('   ')
    nodes = []
    links = []
    #1 查询两个药材对应组分 source：药材 target：组分
    for herb in herbs:
        nodes.append({'id': herb, 'class': 'herb', 'group': 0, 'size': 15})
        molecules=Herbsmol.objects.filter(herbs_name=herb).values_list('molecular_name',flat=True)
        for molecule in molecules:
            nodes.append({'id': molecule, 'class': 'Molecule', 'group': 1, 'size': 12})
            links.append({'source': herb, 'target': molecule, 'value': 3})
            targets=Tamol.objects.filter(molecular_name=molecule).values_list('tg_name',flat=True)
            #2 查询组分对应靶标 source：药材 target：靶标
            for target in targets:
                nodes.append({'id': target, 'class': 'Target', 'group': 2, 'size': 10})
                links.append({'source': herb, 'target': target, 'value': 3})
                #3 查询每个靶标对应疾病 source：靶标 target：疾病
                disease=Target.objects.filter(target_name=target).values_list('diseasesName',flat=True)
                if disease:
                    diseaseNames=disease[0].split(';')
                    for diseaseName in diseaseNames:
                        nodes.append({'id': diseaseName, 'class': 'Molecule', 'group': 3, 'size': 8})
                        links.append({'source': target, 'target': diseaseName, 'value': 3})
    #去重
    node=[]
    for i in nodes:
        if i not in node:
            node.append(i)
    #组合成json字符串
    arg=json.dumps({'nodes': node, 'links': links})
    return render(request,'PredictKG.html',{'arg':arg,'herb1':herbs[0],'herb2':herbs[1]})

apps/Graphapp/templates/Predictindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %}药对配伍预测{% endblock %}

{% block content %}
<br>
            <div class="container-fluid">
                <!-- Page Header-->
                <header>
                    <h1 class="h3 display">药对配伍预测</h1>
                </header>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{% url 'Graphapp:Predictindex' %}" method="get">
                                    <div class="form-group row" style="margin-left: 15%;" >
                                        <label class="form-control-label" >药材名称</label>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-text1" value="{{ search_text1 }}" placeholder="示例：金银花" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-4">
                                            <input type="text" class="form-control" name="search-text2" value="{{ search_text2 }}" placeholder="示例：甘草" style="vertical-align: middle;">
                                        </div>
                                        <div class="col-sm-2 " style="text-align: right;">
                                            <button class="btn btn-primary" type="submit">检索</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

    {% if search_text1 or search_text2 %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {% if herb_list %}
                            <h2 class="h5">搜索结果</h2>
                                <div class="list-group">
                                {% for herb in herb_list %}
                                  <a href="{% url 'Graphapp:PredictKG' herb %} " class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                      <h5 class="mb-1" >{{ herb }}</h5>
                                    </div>
                                  </a>
                                {% endfor %}
                                </div>
                                <br>
                                <div class="pagination row">
                                    <div class="m-auto">
                                        <span class="step-links">
                                            <!-- 如果不是第一页，则显示上翻按钮 -->
                                            {% if herb_list.has_previous %}
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page=1" class="btn btn-success">
                                                    &laquo; 1
                                                </a>
                                                <span>...</span>
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ herb_list.previous_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ herb_list.previous_page_number }}
                                                </a>
                                            {% endif %}
                                            <!-- 当前页面 -->
                                            <span class="current btn btn-success btn-lg">
                                                {{ herb_list.number }}
                                            </span>

                                            <!-- 如果不是最末页，则显示下翻按钮 -->
                                            {% if herb_list.has_next %}
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ herb_list.next_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ herb_list.next_page_number }}
                                                </a>
                                                <span>...</span>
                                                <a href="?search-text1={{ search_text1 }}&search-text2={{ search_text2 }}&page={{ herb_list.paginator.num_pages }}"
                                                   class="btn btn-success"
                                                >
                                                    {{ herb_list.paginator.num_pages }} &raquo;
                                                </a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <h2 class="card-title">未找到相关结果</h2>
                                <br>
                                <p class="card-subtitle mb-2 text-muted">您可以:</p>
                                <p class="card-text">1.检查检索词是否有误或者过于复杂</p>
                                {% if search_text1 and search_text2 %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text1 }}”和“{{ search_text2 }}”</p>
                                {% elif search_text1 %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text1 }}”</p>
                                {% else %}
                                    <p class="card-text">2.在其他栏目中搜索“{{ search_text2 }}”</p>
                                {% endif %}
                                    <a href="{% url 'Graphapp:Predictindex' %}" class="card-link">返回</a>
                             {% endif %}
                        </div>
                    </div>
                </div>
        </div>
{% endif %}
    </div>
{% endblock %}

apps/Graphapp/templates/Recipehcindex.html
{% extends 'base.html' %}
{% load static %}
{% block title %}方剂-药材-组分知识图谱{% endblock %}

{% block content %}
<br>
        <div class="container-fluid">
            <!-- Page Header-->
            <header>
                <h1 class="h3 display">方剂-药材-组分知识图谱</h1>
            </header>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                        <form action="{% url 'Graphapp:Recipehcindex' %}" method="get">
                            <div class="form-group row" style="margin-left: 25%;" >
                                <label class="form-control-label" style=" margin-bottom: 0;padding-top: 0.5rem;">方剂名称</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="search-recipehcKG-text" value="{{ search_text }}" placeholder="示例：软坚清脉方" style="vertical-align: middle;">
                                </div>
                                <div class="col-sm-2 " style="text-align: right;">
                                    <button class="btn btn-primary" >检索</button>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
    {% if search_text %}
        <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            {% if recipe_list %}
                            <h2 class="h5">搜索结果</h2>
                                <div class="list-group">
                                {% for recipe in recipe_list %}
                                  <a href="{% url 'Graphapp:RecipehcKG' recipe %} " class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                      <h5 class="mb-1" >{{ recipe }}</h5>
                                    </div>
                                  </a>
                                {% endfor %}
                                </div>
                            <br>
                            <div class="pagination row">
                                    <div class="m-auto">
                                        <span class="step-links">
                                            <!-- 如果不是第一页，则显示上翻按钮 -->
                                            {% if recipe_list.has_previous %}
                                                <a href="?search-recipehcKG-text={{ search_text }}&page=1" class="btn btn-success">
                                                    &laquo; 1
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipehcKG-text={{ search_text }}&page={{ recipe_list.previous_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.previous_page_number }}
                                                </a>
                                            {% endif %}

                                            <!-- 当前页面 -->
                                            <span class="current btn btn-success btn-lg">
                                                {{ recipe_list.number }}
                                            </span>

                                            <!-- 如果不是最末页，则显示下翻按钮 -->
                                            {% if recipe_list.has_next %}
                                                <a href="?search-recipehcKG-text={{ search_text }}&page={{ recipe_list.next_page_number }}"
                                                   class="btn btn-secondary"
                                                >
                                                    {{ recipe_list.next_page_number }}
                                                </a>
                                                <span>...</span>
                                                <a href="?search-recipehcKG-text={{ search_text }}&page={{ recipe_list.paginator.num_pages }}"
                                                   class="btn btn-success"
                                                >
                                                    {{ recipe_list.paginator.num_pages }} &raquo;
                                                </a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                            {% else %}
                                <h2 class="card-title">未找到相关结果</h2>
                                <br>
                                <p class="card-subtitle mb-2 text-muted">您可以:</p>
                                <p class="card-text">1.检查检索词是否有误或者过于复杂</p>
                                <p class="card-text">2.在其他栏目中搜索“{{ search_text }}”</p>
                                <a href="{% url 'Graphapp:Recipehcindex' %}" class="card-link">返回</a>
                             {% endif %}
                        </div>
                    </div>
                </div>
        </div>
{% endif %}
        </div>
{% endblock %}

apps/Graphapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>方剂知识图谱</title>
    <meta name="description" content="">
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto-->
{#    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">#}
    <!-- jQuery Circle-->
{#    <link rel="stylesheet" href="{% static 'css/mobile_progress_circle-1.0.0.min.css' %}">#}
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="{% static 'vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Favicon-->
{#    <link rel="shortcut icon" href="img/favicon.ico">#}
      <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/nav-tabs.css' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="https://at.alicdn.com/t/font_1829660_8u32drfcne.js"></script>
      {% block css %}{% endblock %}
  </head>
  <body>
    <style type="text/css">
    .icon {
       width: 1.7em; height: 1.7em;
       vertical-align: -0.4em;
       fill: currentColor;
       overflow: hidden;
    }
</style>
        <!-- Side Navbar -->
    <nav class="side-navbar">
      <div class="side-navbar-wrapper">
        <!-- Sidebar Header    -->
        <div class="sidenav-header d-flex align-items-center justify-content-center">
          <div class="sidenav-header-inner text-center">
            <h2 class="h5">菜单</h2>
          </div>
            <!-- Small Brand information, appears on minimized sidebar-->
          <div class="sidenav-header-logo"><div class="brand-small text-center"><strong>MENU</strong></div></div>
        </div>
        <!-- Sidebar Navigation Menus-->
        <div class="main-menu">
          <ul id="side-main-menu" class="side-menu list-unstyled">
            <li><a href="{% url 'Formula:index' %}"> <svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-formula"></use></svg>中药方剂知识库 </a> </li>
            <li><a href="{% url 'Herb:herbindex' %}"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-herb"></use></svg>药材知识库                           </a></li>
            <li><a href="{% url 'Ingredients:Comindex' %}"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-ingredient"></use></svg>组分知识库                           </a></li>
            <li><a href="{% url 'Target:Targetindex' %}"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-target"></use></svg>靶标知识库                           </a></li>
            <li><a href="#Dropdown1" aria-expanded="false" data-toggle="collapse"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-KG"></use></svg>方剂知识图谱 </a>
              <ul id="Dropdown1" class="collapse list-unstyled ">
                <li><a href="{% url 'Graphapp:Recipehcindex' %}">方剂-药材-组分图谱</a></li>
                <li><a href="{% url 'Graphapp:Recipehmiindex' %}">方剂-药材-靶标-疾病图谱</a></li>
              </ul>
            </li>
            <li><a href="#Dropdown2" aria-expanded="false" data-toggle="collapse"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-analysis"></use></svg>成分对比分析      </a>
              <ul id="Dropdown2" class="collapse list-unstyled ">
                <li><a href="{% url 'Analysis:Analysisindex' %}">药材成分对比分析                        </a></li>
                <li><a href="{% url 'Analysis:FAnalyindex' %}">方剂成分对比分析                        </a></li>
              </ul>
            <li><a href="{% url 'Combination:FComindex' %}"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-combination"></use></svg>方剂配伍(加减化裁)                        </a></li>
            <li><a href="{% url 'Graphapp:Predictindex' %}"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-predict"></use></svg>药对配伍预测                       </a></li>
            <li><a href="{% url 'Formula:ADRindex' %}"> <svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-ADR"></use></svg>不良反应                         </a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="page">
      <!-- navbar-->
      <header class="header">
        <nav class="navbar">
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><svg class="icon" aria-hidden="true"
    xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="#icon-bar"></use></svg></a>
                <a href="{% url 'Formula:index' %}" class="navbar-brand">
                    <div class="brand-text d-none d-md-inline-block"><span style="font-size:19px">方剂</span><strong class="text-primary">知识图谱</strong></div>
                </a>
              </div>
            </div>
          </div>
        </nav>
      </header>
        {% block content %} {% endblock %}
    </div>

<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
<script src="{% static 'vendor/jquery-validation/jquery.validate.min.js' %}"></script>
<script src="{% static 'vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>